### ISSUE TITLE
Commands have no icon when added to Quick Action Bar on mobile

### ISSUE THREAD

**Issue by zkat** [cwegrzyn/iron-vault#57]
this makes it very hard to distinguish commands in the QAB from each other.

**Comment by AstralTomate** [comment]
Here are some suggestions, I also added some of the icons you use in the journal, but all other icons are just black and white so im not sure if that is the best fit. I also added emojis for the moves that have no counterpart in the journal yet (they are in brackets):

- Make a Move is already the lightning, could also be https://lucide.dev/icons/circle-play or (⚡),
- Burn Momentum could be the flame https://lucide.dev/icons/flame or 🔥,
- Advance a Progress Tack could be some arrow https://lucide.dev/icons/chevrons-right or (⏩),
- Ask the Oracle (i didnt find a glasbowl) could be a split https://lucide.dev/icons/split  or 🔮,
- Advance a Clock https://lucide.dev/icons/alarm-clock-plus or 🕒,
- Create a Progress Track something with a plus https://lucide.dev/icons/badge-plus 🚀,
- Generate an entity https://lucide.dev/icons/package-plus or https://lucide.dev/icons/user-plus or https://lucide.dev/icons/smile-plus or 🔁 or (🔀),
- Add asset to character https://lucide.dev/icons/gem  or https://lucide.dev/icons/gift or (💎,📦,🎁,🧙‍♂️) ,
- Take on a Meter https://lucide.dev/icons/square-plus or (➕),
- Suffer on a Meter https://lucide.dev/icons/square-minus or (➖),
- Toggle Displaying Mechanics, maybe an eye https://lucide.dev/icons/eye-off or (⚙️,🔩,👁️)

I don't really care if you use my suggestions, I'm just happy if they get added at some point. Keep up the good work!

**Comment by cwegrzyn** [comment]
Thanks so much for the suggestions @AstralTomate !

One big question in my mind is whether to go all in on +/- for add/subtract (in which case we need to avoid +/- for creation/removal)

Here is what I'm thinking:

> * Make a Move is already the lightning, could also be https://lucide.dev/icons/circle-play or (⚡),

Keeping as-is: https://lucide.dev/icons/zap

> * Burn Momentum could be the flame https://lucide.dev/icons/flame or 🔥,

Adopted suggestion: https://lucide.dev/icons/flame

> * Ask the Oracle (i didnt find a glasbowl) could be a split https://lucide.dev/icons/split  or 🔮,

Tweaked existing one from https://lucide.dev/icons/circle-help to https://lucide.dev/icons/message-circle-question . We can't match the crystal ball in lucide, and I feel like the question-in-a-chat-bubble pretty clearly conveys "ask a question".

> * Advance a Clock https://lucide.dev/icons/alarm-clock-plus or 🕒,

For clocks, I'm thinking:

* Create: https://lucide.dev/icons/alarm-clock
* Add segment: https://lucide.dev/icons/alarm-clock-plus
* Remove segment: https://lucide.dev/icons/alarm-clock-minus
* Abandon: https://lucide.dev/icons/alarm-clock-off

> * Create a Progress Track something with a plus https://lucide.dev/icons/badge-plus 🚀,
> * Advance a Progress Tack could be some arrow https://lucide.dev/icons/chevrons-right or (⏩),

For progress tracks, I'm thinking:

* Create: https://lucide.dev/icons/square-pen (could use square-plus-- but that may confuse with add segment)
* Add progress: https://lucide.dev/icons/square-chevron-right (could use square-plus though and match alarm clocks)
* Remove progress: https://lucide.dev/icons/square-chevron-left (could use square-minus)
* Complete a track: https://lucide.dev/icons/square-check

If we have separate commands for completing a track with success vs failure, I might use square-check for success and square-x for failure.

Alternatively, maybe the `copy` series of images would be better, since we get two boxes. But then we'd have to use plus/minus... But maybe that's better for analogy with clocks anyway?

> * Generate an entity https://lucide.dev/icons/package-plus or https://lucide.dev/icons/user-plus or https://lucide.dev/icons/smile-plus or 🔁 or (🔀),

Hmm, `package-plus` makes sense!

> * Add asset to character https://lucide.dev/icons/gem  or https://lucide.dev/icons/gift or (💎,📦,🎁,🧙‍♂️) ,

I like `gem`. I've considered making the command pop up some sort of modal that lets you manage (add/remove) assets, so that works with not having plus/minus versions.

> * Take on a Meter https://lucide.dev/icons/square-plus or (➕),
> * Suffer on a Meter https://lucide.dev/icons/square-minus or (➖),

I think this depends on whether or not we go all in on +/-. If we go all in on plus/minus, then `square-plus` would be for meters, so maybe `diamond-plus` or `circle-plus`.

If we stay away from +/-, maybe https://lucide.dev/icons/trending-up and https://lucide.dev/icons/trending-down for these? Especially since it always feels like these things snowball!

> * Toggle Displaying Mechanics, maybe an eye https://lucide.dev/icons/eye-off or (⚙️,🔩,👁️)

Makes sense!

> 
> I don't really care if you use my suggestions, I'm just happy if they get added at some point. Keep up the good work!

Thanks again for going through and finding these. Generating the first list is always the hardest step to overcome!

**Comment by AstralTomate** [comment]
Hey @cwegrzyn, 

first of all I agree with your suggestions and tweaks. 
Regarding the pluses and minuses I'm not really sure what would be the more intuitive way of doing it. But probably not using plus and minus for advancing is a good idea. 

As a general thought: When the icons are put in order in the hotbar it might be anyways obvious what the advance button does if it is placed next to its corresponding create button (like creating a clock for example). So it would be even possible to use for all the advance and rewind actions the same icons (clocks, progress bars, meters, vows...)
