### ISSUE TITLE
Progress bar error when starting with a link

### ISSUE THREAD

**Issue by AllieWade** [cwegrzyn/iron-vault#93]
v0.19.1 running on Obsidian v1.5.12 (installer version 1.4.13)

Progress bars that begin with a link throw an error ("Error rendering track: track file is invalid").

To reproduce: create a progress track file whose name attribute begins with a link, such as the below. Changing the name value by adding a letter in front of the link makes it work. (Apostrophes substituted for backticks because code block.)

---
tags:
  - incomplete
forgedkind: progress
tracktype: Connection
complete: false
unbounded: false
name: [[Raven Steward]]
progress: 4
rank: formidable
---

'''forged-track
'''

**Comment by zkat** [comment]
This is a yaml issue. The `[[Raven Steward]]` is being read as an array-of-array-of-strings, which fails validation because that's supposed to just be a string. Adding a single letter before the `[` works because it makes yaml interpret it as a string again. Yaml is weird and annoying like that.

To fix it, simply wrap it in double quotes.

We have #81 for showing more helpful errors when validation fails, so you're not just left wondering wtf you did wrong.
